name: index
version: "1.0.2"
grade: stable
base: core20
summary: Simple BMI Calculator
description: A simple body mass index calculator. The program makes it easy to calculate BMI based on data on gender, weight, height and wrist circumference. The results of the calculations are approximate, are for informational purposes only and cannot be used for medical purposes.
icon: data/icons/com.github.alexkdeveloper.bmi.svg
confinement: strict
parts:
  index:
    after: [desktop-gnome-platform]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/alexkdeveloper/bmi.git
    build-packages:
        - valac
        - build-essential
        - intltool
        - libgee-0.8-dev
        - debhelper
        - libgtk-3-dev
        - libgranite-dev
        - libgtksourceview-3.0-dev
    stage-packages:
        - gobject-introspection
        - libgdk-pixbuf2.0-0
        - libgee-0.8-2
        - libgtk-3-0
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - valac
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
apps:
  index:
    command: usr/bin/com.github.alexkdeveloper.bmi
    desktop: usr/share/applications/com.github.alexkdeveloper.bmi.desktop
    plugs:
      - x11
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
    slots: [ dbus-index ]
slots:
  dbus-index:
    interface: dbus
    bus: session
    name: com.github.alexkdeveloper.bmi
plugs:
  gnome-3-38-2004:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-38-2004
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
